### PR TITLE
bump ravendb packages version

### PR DESCRIPTION
**Pull request by serbrech**
nothing more than the title says. What are the plans to publish a package?
We started a project now, and this starts to feel abandoned. Satellite packages are out of date and the latest publish nuget is far behind (5.2.0 that includes CommonDomain vs 6.0 and extracted Domain)

### CODE REVIEW

**Comment by andreabalducci** [comment]
V6 is in the works, team meeting this week to schedule first public beta.

**Comment by andreabalducci** [comment]
For your project don't use Obsoleted methods / api, I dropped the sync / async /noop Dispatcher last week (on a feature branch, soon on develop)

**Comment by kjersti** [comment]
Is there any way we can help to get the new version on NuGet?

**Comment by serbrech** [comment]
There isnt much to do really, no breaking APIs,
So nothing that we can do, the package owners need to publish it.
I just updated it on my system and pushed a package to our local nuget
server

/S

**Comment by alkampfergit** [comment]
Hi,

this pull request only bumps the nuget version of ravendb so it could be published simply as an hotfix with version 5.2.1.

Gian Maria.

**Pull request closed without merging**
